name: xmage-snap
base: core24
version: 'dev-0.2.2'
summary: XMage snap application
description: |
  XMage allows you to play Magic the Gathering games with other players.

grade: devel
confinement: devmode

apps:
  xmage-snap:
    command-chain:
      - setup-xmage.sh
    command: start-xmage.sh
    plugs:
      - home
      - network
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - pulseaudio
      - audio-playback
      - system-observe

parts:
  xmage-snap:
    #source: http://xmage.today/files/mage-full_1.4.51-dev_2024-06-06_19-55.zip
    source: .
    plugin: dump
    stage-packages:
      - openjdk-21-jre
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libglu1-mesa
      - libgl1-mesa-dri
      - libglx-mesa0
      - libpulse0
      - libasound2

environment:
  XMAGE_HOME: $SNAP_USER_COMMON/xmage
  JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

layout:
  /usr/lib/jvm/java-21-openjdk-amd64:
    bind: $SNAP/usr/lib/jvm/java-21-openjdk-amd64
