name: xmage-snap
base: core24
version: 'dev-0.1'
summary: Simple XMage Snap package with bundled java
description: |
  Simple XMage Snap package with bundled java

grade: devel
confinement: devmode

apps:
  xmage-snap:
      command: usr/lib/jvm/java-21-openjdk-amd64/bin/java -jar $SNAP_USER_DATA/XMageLauncher-0.3.8.jar
      plugs: [home, desktop, x11, wayland, network, network-bind]
      environment: 
          JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAP_ARCH
          PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH:$SNAP/common

parts:
    xmage-snap:
        source: http://xmage.today/files/mage-full_1.4.51-dev_2024-06-06_19-55.zip
        plugin: dump
        build-packages:
            - openjdk-21-jdk
        stage-packages:
            - gtk2-engines-murrine
            - hicolor-icon-theme
            - openjdk-21-jdk