#!/bin/sh

# Ensure the /opt/xmage directory exists
if [ ! -d "$SNAP_COMMON"/opt/xmage ]; then
    mkdir -p "$SNAP_COMMON"/opt/xmage;
fi

# Copy necessary files to /opt/xmage
cp -rp "$SNAP"/XMageLauncher-0.3.8.jar "$SNAP_COMMON"/opt/xmage/
cp -rp "$SNAP"/installed.properties "$SNAP_COMMON"/opt/xmage/
cp -rp "$SNAP"/xmage/ "$SNAP_COMMON"/opt/xmage/

# Change ownership to the current user and set appropriate permissions
chown -R "$USER:$USER $SNAP_COMMON"/opt/xmage
chmod -R 755 "$SNAP_COMMON"/opt/xmage