#!/bin/sh

# Ensure the bin directory exists in the snap environment
mkdir -p "$SNAP"/bin

# Copy the start-xmage.sh script to the bin directory in the snap environment
cp "$SNAP_DATA"/start-xmage.sh "$SNAP"/bin/
chmod +x "$SNAP"/bin/start-xmage.sh
